language: generic 
sudo: required
services:
  - docker 


before_install:
  - docker build -t federicoidarraga/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true federicoidarraga/docker-react npm run test